# Generated by Django 2.2.3 on 2019-08-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='company_regulations',
        ),
    ]
