# Generated by Django 2.2.3 on 2019-10-07 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
