# Generated by Django 2.2.3 on 2019-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_requests', '0002_auto_20190829_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='reason',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
