# Generated by Django 2.2.3 on 2019-08-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission_requests', '0003_permissionrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='documents.Document'),
        ),
    ]
