# Generated by Django 2.2.3 on 2019-08-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_requests', '0004_auto_20190829_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='canceled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='viewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
