# Generated by Django 2.2.3 on 2019-08-29 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permission_requests', '0005_auto_20190829_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionrequest',
            old_name='user_request',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='canceled_date',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='has_approved',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='has_canceled',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='user_approval',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='user_cancellation',
        ),
        migrations.RemoveField(
            model_name='permissionrequest',
            name='user_view',
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='action_reason',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Approved'), (2, 'Canceled'), (3, 'Request')], default=3),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='user_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_action', to=settings.AUTH_USER_MODEL),
        ),
    ]
