# Generated by Django 2.2.3 on 2019-08-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission_requests', '0006_auto_20190829_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionrequest',
            old_name='documents',
            new_name='document',
        ),
    ]
