# Generated by Django 2.2.3 on 2019-08-11 16:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import document_management.core.utils
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('subject', models.CharField(max_length=64)),
                ('effective_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Contract'), (2, 'MoU'), (3, 'Reading News')])),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Construction'), (2, 'Property'), (3, 'Other')])),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'Public')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ongoing'), (2, 'Done'), (3, 'Expired')], default=1)),
                ('job_specification', models.CharField(blank=True, max_length=256, null=True)),
                ('beginning_period', models.CharField(blank=True, max_length=4, null=True)),
                ('ending_period', models.CharField(blank=True, max_length=4, null=True)),
                ('retention_period', models.IntegerField(blank=True, max_length=4, null=True)),
                ('total_document', models.IntegerField(default=0)),
                ('total_addendum', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='locations.Location')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partners.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=document_management.core.utils.FilenameGenerator('document_file'))),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='documents.Document')),
            ],
        ),
    ]
