# Generated by Django 2.2.3 on 2019-10-20 16:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import document_management.core.utils
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('subject', models.CharField(max_length=256)),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Contract'), (2, 'MoU'), (3, 'Offical Record'), (4, 'Company Regulation')])),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Construction'), (2, 'Property'), (3, 'Director Decisions'), (4, 'Circular Letter'), (5, 'Other')])),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Private'), (2, 'Public')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ongoing'), (2, 'Done'), (3, 'Expired')], default=1)),
                ('job_specification', models.CharField(blank=True, max_length=256)),
                ('retention_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_document', models.PositiveSmallIntegerField(default=0)),
                ('total_addendum', models.PositiveSmallIntegerField(default=0)),
                ('total_official_record', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='locations.Location')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partners.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField(blank=True, null=True)),
                ('document_subject', models.CharField(blank=True, max_length=64, null=True)),
                ('addendum_id', models.IntegerField(blank=True, null=True)),
                ('addendum_subject', models.CharField(blank=True, max_length=64, null=True)),
                ('official_record_id', models.IntegerField(blank=True, null=True)),
                ('official_record_subject', models.CharField(blank=True, max_length=64, null=True)),
                ('action', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Create Contract'), (2, 'Update Contract'), (3, 'Delete Contract'), (4, 'Upload Contract File'), (5, 'Delete Contract File'), (6, 'Update Contract Status'), (7, 'Update Contract Record Status'), (11, 'Create MoU'), (12, 'Update MoU'), (13, 'Delete MoU'), (14, 'Upload MoU File'), (15, 'Delete MoU File'), (16, 'Update MoU Status'), (17, 'Update MoU Record Status'), (21, 'Create Official Record'), (22, 'Update Official Record'), (23, 'Delete Official Record'), (24, 'Upload Official Record File'), (25, 'Delete Official Record File'), (26, 'Update Official Record Status'), (27, 'Update Offical Record Record Status'), (31, 'Create Company Regulation'), (32, 'Update Company Regulation'), (33, 'Delete Company Regulation'), (34, 'Upload Company Regulation File'), (35, 'Delete Company Regulation File'), (36, 'Update Company Regulation Status'), (37, 'Update Company Regulation Record Status'), (41, 'Create Addendum Relational'), (42, 'Update Addendum Relational'), (43, 'Delete Addendum Relational'), (44, 'Upload Addendum Relational File'), (45, 'Delete Addendum Relational File'), (46, 'Update Addendum Relational Record Status'), (51, 'Create Official Record Relational'), (52, 'Update Official Record Relational'), (53, 'Delete Official Record Relational'), (54, 'Upload Official Record Relational File'), (55, 'Delete Official Record Relational File'), (56, 'Update Official Record Relational Record Status')], null=True)),
                ('value', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=document_management.core.utils.FilenameGenerator('document_file'))),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.Document')),
            ],
        ),
    ]
