# Generated by Django 2.2.3 on 2019-08-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Construction'), (2, 'Property'), (3, 'Director Decisions'), (4, 'Circular Letter'), (5, 'Other')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Contract'), (2, 'MoU'), (3, 'Offical Record'), (4, 'Company Regulation')]),
        ),
        migrations.AlterField(
            model_name='documentlogs',
            name='action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Create Contract'), (2, 'Update Contract'), (3, 'Delete Contract'), (4, 'Upload Contract File'), (5, 'Delete Contract File'), (6, 'Update Contract Status'), (7, 'Update Contract Record Status'), (11, 'Create MoU'), (12, 'Update MoU'), (13, 'Delete MoU'), (14, 'Upload MoU File'), (15, 'Delete MoU File'), (16, 'Update MoU Status'), (17, 'Update MoU Record Status'), (21, 'Create Official Record'), (22, 'Update Official Record'), (23, 'Delete Official Record'), (24, 'Upload Official Record File'), (25, 'Delete Official Record File'), (26, 'Update Official Record Status'), (27, 'Update Offical Record Record Status'), (31, 'Create Addendum Relational'), (32, 'Update Addendum Relational'), (33, 'Delete Addendum Relational'), (34, 'Upload File Addendum Relational'), (35, 'Delete File Addendum Relational'), (36, 'Update Addendum Relational Record Status'), (41, 'Create Official Record Relational'), (42, 'Update Official Record Relational'), (43, 'Delete Official Record Relational'), (44, 'Upload Official Record File Relational'), (45, 'Delete Official Record File Relational'), (46, 'Update Official Record Relational Record Status')], null=True),
        ),
    ]
