# Generated by Django 2.2.3 on 2019-10-15 14:18

from django.db import migrations, models
import document_management.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=document_management.core.utils.FilenameGenerator('document_file')),
        ),
    ]
