# Generated by Django 2.2.3 on 2019-10-20 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentlogs',
            name='action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Create Contract'), (2, 'Update Contract'), (3, 'Delete Contract'), (4, 'Upload Contract File'), (5, 'Delete Contract File'), (6, 'Update Contract Status'), (7, 'Update Contract Record Status'), (11, 'Create MoU'), (12, 'Update MoU'), (13, 'Delete MoU'), (14, 'Upload MoU File'), (15, 'Delete MoU File'), (16, 'Update MoU Status'), (17, 'Update MoU Record Status'), (21, 'Create Official Record'), (22, 'Update Official Record'), (23, 'Delete Official Record'), (24, 'Upload Official Record File'), (25, 'Delete Official Record File'), (26, 'Update Official Record Status'), (27, 'Update Offical Record Record Status'), (31, 'Create Company Regulation'), (32, 'Update Company Regulation'), (33, 'Delete Company Regulation'), (34, 'Upload Company Regulation File'), (35, 'Delete Company Regulation File'), (36, 'Update Company Regulation Status'), (37, 'Update Company Regulation Record Status'), (41, 'Create Addendum Relational'), (42, 'Update Addendum Relational'), (43, 'Delete Addendum Relational'), (44, 'Upload Addendum Relational File'), (45, 'Delete Addendum Relational File'), (46, 'Update Addendum Relational Record Status'), (51, 'Create Official Record Relational'), (52, 'Update Official Record Relational'), (53, 'Delete Official Record Relational'), (54, 'Upload Official Record Relational File'), (55, 'Delete Official Record Relational File'), (56, 'Update Official Record Relational Record Status')], null=True),
        ),
    ]
