# Generated by Django 2.2.3 on 2019-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ongoing'), (2, 'Done'), (3, 'Expired')], default=1),
        ),
    ]
