# Generated by Django 2.2.3 on 2019-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20190816_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentlogs',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='documentlogs',
            name='deleted_date',
        ),
        migrations.AlterField(
            model_name='documentlogs',
            name='action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Create Document'), (2, 'Update Document'), (3, 'Delete Document'), (4, 'Upload Document'), (5, 'Update Document Status'), (6, 'Update Record Status'), (7, 'Create Addendum'), (8, 'Update Addendum'), (9, 'Delete Addendum'), (10, 'Upload Addendum')], null=True),
        ),
    ]
