# Generated by Django 2.2.3 on 2019-08-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20190822_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlogs',
            name='addendum_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentlogs',
            name='addendum_subject',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
