# Generated by Django 2.2.3 on 2019-08-15 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_auto_20190815_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='deleted_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_date',
        ),
        migrations.CreateModel(
            name='DocumentLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_document_logs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_logs', to='documents.Document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_document_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
