# Generated by Django 2.2.3 on 2019-08-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20190822_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlogs',
            name='document_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentlogs',
            name='document_subject',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
