# Generated by Django 2.2.3 on 2019-08-15 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20190815_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='documentlogs',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentlogs',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='documentlogs',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
