# Generated by Django 2.2.3 on 2019-08-15 18:56

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('director', models.CharField(blank=True, max_length=64, null=True)),
                ('person_in_charge', models.CharField(blank=True, max_length=64, null=True)),
                ('business_sector', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Aneka Industri'), (2, 'Barang Konsumsi'), (3, 'Industri Dasar dan Kimia'), (4, 'Infrastruktur'), (5, 'Jasa'), (6, 'Keuangan'), (7, 'Perdagangan'), (8, 'Pertambangan'), (9, 'Pertanian'), (10, 'Properti'), (11, 'Transportasi')], null=True)),
                ('address', models.CharField(max_length=256)),
                ('npwp', models.CharField(max_length=32)),
                ('siup', models.CharField(max_length=32)),
                ('ptkp', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=32)),
                ('fax', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
