# Generated by Django 2.2.3 on 2019-08-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='partner',
            name='fax',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='npwp',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='partner',
            name='ptkp',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='partner',
            name='siup',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='partner',
            name='telephone',
            field=models.CharField(max_length=32),
        ),
    ]
