# Generated by Django 2.2.3 on 2019-08-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialrecord',
            name='number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
