# Generated by Django 2.2.3 on 2019-10-20 00:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('official_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialrecord',
            name='description',
            field=models.TextField(blank=True, default=datetime.datetime(2019, 10, 20, 0, 38, 15, 381263, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
