# Generated by Django 2.2.3 on 2019-08-22 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addendums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addendum',
            name='amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='addendum',
            name='beginning_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addendum',
            name='ending_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addendum',
            name='job_specification',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='addendum',
            name='retention_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
