# Generated by Django 2.2.3 on 2019-10-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('addendums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addendum',
            name='number',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='addendum',
            unique_together={('document', 'number')},
        ),
    ]
