# Generated by Django 2.2.3 on 2019-08-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addendums', '0002_auto_20190822_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addendumfile',
            name='addendum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='addendums.Addendum'),
        ),
    ]
