# Generated by Django 2.2.3 on 2019-10-20 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addendums', '0002_auto_20191008_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addendum',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
